//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolCareSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public string ProductName { get; set; }
        public string Service_Issue { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> RequestedAt { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Status { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual User User { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
